name: 'Hello Typescript action'
description: 'Simple example GitHub action built with Typescript'
author: 'whatasame'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  milliseconds:
    description: 'Time for waiting in milliseconds'
    required: true
    default: '1000'
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: 'World'

# Define your outputs here.
outputs:
  time:
    description: 'The time we greeted you'

runs:
  using: node20
  main: dist/index.js
